general:
  verbose:true
steps:
  gctsDeploy:
    host: 'https://fc-pun01-hana.india.rapidigm.com:8001'
    client: '300'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'DEV003'
  gctsExecuteABAPUnitTests:
    host: 'https://fc-pun01-hana.india.rapidigm.com:8001'
    client: '300'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'DEV003'
